### ISSUE TITLE
copy issue

### ISSUE THREAD

**Issue by noammiz007** [Finicalmist/CopyCode#3]
hmm, there is an issue that i always have to click twice to copy. and one click doesn't work.

can you fix it please?

**Comment by KaKi87** [comment]
Well, whatever how many times I click, it doesn't work 😅

**Comment by twnlink** [comment]
I've created a fix for it, however the author is long gone so I don't expect my fix to be merged.
https://github.com/Cr3atable/CopyCode

**Comment by Finicalmist** [comment]
Fixed by @Cr3atable , thanks i guess

**Comment by KaKi87** [comment]
Thanks ! Only 1 line of code to fix it 😂
